--- 
- hosts: all
  user: root 
  become: true
  
  tasks:
  - name: Reset containers
    command: docker container rm -f backend
    ignore_errors: yes
      
  - name: deploy backend container
    command: docker run -d --name backend -p 8080:8080 thibauthumblet/devopsprojectbackend
